# Generated by Django 5.2.17 on 2026-08-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
